platform :ios, '17.5'
use_frameworks!

target 'CryptoTrackerRxSwift' do
    pod 'R.swift'
    # pod 'SDWebImageSwiftUI'
    pod 'SwiftLint'
    # pod 'SwiftyJSON'
end

# Post Install "error: IB Designables: Failed to render and update auto layout ..." fix
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.5'
      end
    end

end